export const LATITUDE = 'LATITUDE';
export const LONGITUDE = 'LONGITUDE';

export const API_REQUEST = 'API_REQUEST';
export const API_REQUEST_SUCCEEDED = 'API_REQUEST_SUCCEEDED';
export const API_REQUEST_FAILED = 'API_REQUEST_FAILED';
export const MODAL_VISIBLE = 'MODAL_VISIBLE';